trees:
  - path: /
    tree: aimmdb:AIMMTree.from_uri
    args:
      uri: ${MONGO_URI}
      username: root
      password: ${MONGO_PASSWORD}
      tree_collection_name: "tree"
      data_collection_name: "measurements"
    access_control:
      access_policy: aimmdb:AIMMAccessPolicy
      args:
        provider: orcid
        access_lists:
          0000-0002-5947-6017: aimmdb:AIMMAccessPolicy.READ  # Dan sees all
          0000-0003-3670-0431: aimmdb:AIMMAccessPolicy.READWRITE  # Joe sees all
          0000-0002-1539-0297: aimmdb:AIMMAccessPolicy.READ  # Dylan sees all
          0000-0002-3337-2930: aimmdb:AIMMAccessPolicy.READ  # Eli sees all
          0000-0002-5269-0125: aimmdb:AIMMAccessPolicy.READ  # Alex sees all
          0000-0003-4351-6085: aimmdb:AIMMAccessPolicy.READ  # Deyu sees all
          0000-0003-0666-8063: aimmdb:AIMMAccessPolicy.READ  # Wanli sees all
          0000-0001-5266-5408: aimmdb:AIMMAccessPolicy.READ  # Zhu sees all
          0000-0002-2473-0193: aimmdb:AIMMAccessPolicy.READ  # Juan sees all
          0000-0003-0922-1363: aimmdb:AIMMAccessPolicy.READ  # Maria sees all
          0000-0002-5181-9513: aimmdb:AIMMAccessPolicy.READ  # Matt sees all
          0000-0001-5651-8405: aimmdb:AIMMAccessPolicy.READ  # Xiaohui sees all
authentication:
  allow_anonymous_access: false
  providers:
    - provider: orcid
      authenticator: aimmdb.authentication:AIMMAuthenticator
      args:
        client_id: ${ORCID_CLIENT_ID}
        client_secret: ${ORCID_CLIENT_SECRET}
        redirect_uri: https://aimm-staging.lbl.gov/api/auth/provider/orcid/login
        public_keys:
          - kty: "RSA"
            e: "AQAB"
            use: "sig"
            kid: "production-orcid-org-7hdmdswarosg3gjujo8agwtazgkp1ojs"
            n: "jxTIntA7YvdfnYkLSN4wk__E2zf_wbb0SV_HLHFvh6a9ENVRD1_rHK0EijlBzikb-1rgDQihJETcgBLsMoZVQqGj8fDUUuxnVHsuGav_bf41PA7E_58HXKPrB2C0cON41f7K3o9TStKpVJOSXBrRWURmNQ64qnSSryn1nCxMzXpaw7VUo409ohybbvN6ngxVy4QR2NCC7Fr0QVdtapxD7zdlwx6lEwGemuqs_oG5oDtrRuRgeOHmRps2R6gG5oc-JqVMrVRv6F9h4ja3UgxCDBQjOVT1BFPWmMHnHCsVYLqbbXkZUfvP2sO1dJiYd_zrQhi-FtNth9qrLLv3gkgtwQ"
            alg: RS256
        token_uri: https://orcid.org/oauth/token
        authorization_endpoint: https://orcid.org/oauth/authorize?response_type=code&scope=openid&client_id={client_id}&redirect_uri={redirect_uri}
        confirmation_message: You have logged with ORCID.
  tiled_admins:
    - provider: orcid
      id: 0000-0003-3670-0431
database_uri: "postgresql://tiled:${TILED_DATABASE_PASSWORD}@postgres/tiled"
uvicorn:
  host: 0.0.0.0
  port: 8000
  proxy-headers: true
media_types:
  node:
    application/x-hdf5: aimmdb:serialize_hdf5
