trees:
  - path: /
    tree: aimmdb.adapters.aimm:AIMMCatalog.from_uri
    args:
      uri: mongodb://root:${MONGO_PASSWORD}@mongodb:27017/aimm?authSource=admin
      data_directory: /data
      spec_to_document_model:
        XAS: aimmdb.schemas:XASDocument
      dataset_to_specs:
        newville:
          - XAS
        aimm:
          - XAS
          - RIXS
        aimm_core:
          - XAS
        iss:
          - XAS
    access_control:
      access_policy: aimmdb.access:DatasetAccessPolicy
      args:
        provider: orcid
        access_lists:
          0000-0003-3670-0431: # Joe
            default: rw
          0000-0002-5947-6017: # Dan
            default: r
            sandbox: rw
            samples: rw
          0000-0002-1539-0297: # Dylan
            default: r
            sandbox: rw
            samples: rw
          0000-0002-3337-2930: # Eli
            default: r
            sandbox: rw
            samples: rw
          0000-0002-5269-0125: # Alex
            default: r
            sandbox: rw
            samples: rw
          0000-0003-4351-6085: # Deyu
            default: r
            sandbox: rw
            samples: rw
          0000-0003-0666-8063: # Wanli
            default: r
            sandbox: rw
            samples: rw
          0000-0001-5266-5408: # Zhu
            default: r
            sandbox: rw
            samples: rw
          0000-0002-2473-0193: # Juan
            default: r
            sandbox: rw
            samples: rw
          0000-0003-0922-1363: # Maria
            default: r
            sandbox: rw
            samples: rw
          0000-0002-5181-9513: # Matt
            default: r
            sandbox: rw
            samples: rw
          0000-0001-5651-8405: # Xiaohui
            default: r
            sandbox: rw
            samples: rw
          0000-0001-9869-9005: # Fanchen
            default: r
            sandbox: rw
            samples: rw
          public:
            newville: r
authentication:
  allow_anonymous_access: true
  providers:
    - provider: orcid
      authenticator: aimmdb.authentication:AIMMAuthenticator
      args:
        client_id: ${ORCID_CLIENT_ID}
        client_secret: ${ORCID_CLIENT_SECRET}
        redirect_uri: https://aimm-staging.lbl.gov/api/auth/provider/orcid/login
        public_keys:
          - kty: "RSA"
            e: "AQAB"
            use: "sig"
            kid: "production-orcid-org-7hdmdswarosg3gjujo8agwtazgkp1ojs"
            n: "jxTIntA7YvdfnYkLSN4wk__E2zf_wbb0SV_HLHFvh6a9ENVRD1_rHK0EijlBzikb-1rgDQihJETcgBLsMoZVQqGj8fDUUuxnVHsuGav_bf41PA7E_58HXKPrB2C0cON41f7K3o9TStKpVJOSXBrRWURmNQ64qnSSryn1nCxMzXpaw7VUo409ohybbvN6ngxVy4QR2NCC7Fr0QVdtapxD7zdlwx6lEwGemuqs_oG5oDtrRuRgeOHmRps2R6gG5oc-JqVMrVRv6F9h4ja3UgxCDBQjOVT1BFPWmMHnHCsVYLqbbXkZUfvP2sO1dJiYd_zrQhi-FtNth9qrLLv3gkgtwQ"
            alg: RS256
        token_uri: https://orcid.org/oauth/token
        authorization_endpoint: https://orcid.org/oauth/authorize?response_type=code&scope=openid&client_id={client_id}&redirect_uri={redirect_uri}
        confirmation_message: You have logged in with ORCID as {id}
  tiled_admins:
    - provider: orcid
      id: 0000-0003-3670-0431
database:
  uri: "postgresql://tiled:${TILED_DATABASE_PASSWORD}@postgres/tiled"
  pool_size: 5
uvicorn:
  host: 0.0.0.0
  port: 8000
